name: dsl-p6-pipeline
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - mkl<2024.1
  - intel-openmp<2024.1
  - numpy
  - pillow
  - scipy
  - shapely
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision=0.20.1
  - pytorch::torchaudio=2.5.1
  - pytorch::pytorch-cuda=12.1
  - pip
  - pip:
      - transformers<=5.8.1
      - huggingface_hub
      - wandb
      - plyfile
      - ffmpeg-python
      - lpips
      - ninja
      - cmake
      - open3d
