name: dsl-p6-nerfacto
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - mkl<2024.1
  - intel-openmp<2024.1
  - setuptools<81
  - wheel
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision=0.20.1
  - pytorch::torchaudio=2.5.1
  - pytorch::pytorch-cuda=12.1
  - pip
  - pip:
      - av==12.3.0
      - ninja
      - nerfstudio==1.1.5
