name: dsl-p6-pipeline
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - mkl<2024.1
  - numpy
  - pillow
  - scipy
  - shapely
  - colmap
  - pytorch=2.5.*
  - torchvision=0.20.*
  - pytorch-cuda=12.1
  - pip
  - pip:
      - transformers
      - huggingface_hub
      - wandb
      - plyfile
      - ffmpeg-python
      - lpips
      - ninja
      - cmake
      - open3d
